
var index = lunr(function () {
    this.field('body');
    this.ref('url');
});

var documentTitles = {};



documentTitles["index.html#aurelia-dialog"] = "Aurelia Dialog";
index.add({
    url: "index.html#aurelia-dialog",
    title: "Aurelia Dialog",
    body: "# Aurelia Dialog  This is a generic dialog component that works with any markup or style.   "
});

documentTitles["index.html#demo"] = "Demo";
index.add({
    url: "index.html#demo",
    title: "Demo",
    body: "## Demo  - [View demo](demo) "
});



documentTitles["changelog.html#changelog"] = "Changelog";
index.add({
    url: "changelog.html#changelog",
    title: "Changelog",
    body: "# Changelog  This changelog is generated by [conventional-changelog](https://www.npmjs.com/package/conventional-changelog) from git commits.   Please [read the conventions](https://github.com/ajoslin/conventional-changelog/blob/master/CONVENTIONS.md) before creating a commit.  &lt;a name\&quot;0.0.1\&quot;&gt;&lt;/a&gt; "
});

documentTitles["changelog.html#001-2015-05-31"] = "0.0.1 (2015-05-31)";
index.add({
    url: "changelog.html#001-2015-05-31",
    title: "0.0.1 (2015-05-31)",
    body: "### 0.0.1 (2015-05-31)  "
});


